### ISSUE TITLE
Yaga Hogs won't breed.

### ISSUE THREAD

**Issue by ThisJustInLocal** [Lykrast/MysticalWildlife#1]
I've managed to capture two of the cuties and put them in a pen, but when I approach them with bread and click on them, they don't get in the mood. Help?

**Comment by Lykrast** [comment]
I can't seem to reproduce the issue on a fresh install on my test instance. What version of the mod are you on (after the minecraft version in the jar's name or in the mod options menu) and what is your mod list ?

**Comment by ThisJustInLocal** [comment]
Uh... I have animania... that might do something? I dunno.

**Comment by Lykrast** [comment]
Give the complete modlist please, might be something you don't suspect.

**Comment by Ghostrider231** [comment]
Did you had them breed recently? Do they show hearts after being feed?

Otherwise, I've spawned yaga hogs or found some, and feed them bread and they breed for me.
